# Generated by Django 5.0.3 on 2024-03-18 21:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0002_mecanico'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='descrucao',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='servico',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geral.oficina', verbose_name='Oficina'),
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('veiculo', models.CharField(help_text='Ex: Honda Fan 160', max_length=100, verbose_name='Veiculo')),
                ('placa', models.CharField(help_text='Ex: BRA-2145', max_length=8, verbose_name='Veiculo')),
                ('previsao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Previsão')),
                ('data_entrada', models.DateTimeField(auto_now=True, verbose_name='Data/Hora Entrada')),
                ('codigo', models.PositiveIntegerField(unique=True, verbose_name='Código OS')),
                ('mecanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geral.mecanico', verbose_name='Mecanico')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.oficina', verbose_name='Oficina')),
                ('servico', models.ManyToManyField(related_name='os', to='servicos.servico', verbose_name='Serviços')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviços',
                'ordering': ['data_entrada'],
            },
        ),
    ]
